baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'AWS Big Data Training Labs'
theme = 'hugo-book'

[menu]
[[menu.after]]
  name = "Labs"
  identifier = "labs"
  pageRef = "/"